// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.v5cn.netty.protobuf.demo.entity;

public final class StudentWrapper {
  private StudentWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_entity_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_entity_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\016message.entity\"?\n\007Stude" +
      "nt\022\020\n\003age\030\001 \001(\005H\000\210\001\001\022\021\n\004name\030\002 \001(\tH\001\210\001\001B" +
      "\006\n\004_ageB\007\n\005_nameB6\n\"cn.v5cn.netty.protob" +
      "uf.demo.entityB\016StudentWrapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_entity_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_entity_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_entity_Student_descriptor,
        new java.lang.String[] { "Age", "Name", "Age", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
