// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.v5cn.netty.protobuf.demo.entity;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.entity.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 age = 1;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>optional int32 age = 1;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
