server:
  port: 9091

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
#
#  ### xxl-job executor address
#xxl.job.executor.appname=xxl-job-executor-sample
#xxl.job.executor.ip=
#xxl.job.executor.port=9999

xxl:
  job:
    admin:
      addresses: http://192.168.31.213:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample2
      ip: 192.168.31.213
      port: 9999
      logpath: ../applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: