server:
  port: 8080
spring:
  application:
    name: api-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    #password:
  security:
    basic:
      enabled: false
    oauth2:
      client:
        access-token-uri: http://localhost:9090/auth/oauth/token
        user-authorization-uri: http://localhost:9090/auth/oauth/authorize
      resource:
        token-info-uri: http://localhost:9090/auth/user
    user:
      name: zhangsan
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:3000/eureka/
      #defaultZone: http://localhost:3000/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

zuul:
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  forceOriginalQueryStringEncoding: true
  routes:
    auth-server:
      path: /demo/**
      sensitiveHeaders:
      serviceId: demo
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 2
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: true
        ConnectTimeout: 20000
        ReadTimeout: 20000
#    user-grant:
#      path: /user-grant/**
#      sensitiveHeaders:
#      serviceId: v5platform-auth
#      ribbon:
#        eager-load:
#          enabled: true
#        MaxAutoRetries: 2
#        MaxAutoRetriesNextServer: 2
#        OkToRetryOnAllOperations: true
#        ConnectTimeout: 20000
#        ReadTimeout: 20000
#    file-service:
#      path: /file-service/**
#      sensitiveHeaders:
#      serviceId: v5platform-fileserver
#      ribbon:
#        eager-load:
#          enabled: true
#        MaxAutoRetries: 2
#        MaxAutoRetriesNextServer: 2
#        OkToRetryOnAllOperations: true
#        ConnectTimeout: 20000
#        ReadTimeout: 20000
#    job-admin:
#      path: /job-admin/**
#      sensitiveHeaders:
#      serviceId: v5platform-job-admin
#      ribbon:
#        eager-load:
#          enabled: true
#        MaxAutoRetries: 2
#        MaxAutoRetriesNextServer: 2
#        OkToRetryOnAllOperations: true
#        ConnectTimeout: 20000
#        ReadTimeout: 20000
  add-proxy-headers: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin,WWW-Authenticate,www-authenticate

hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 60000

proxy:
  auth:
    routes:
      auth-server: oauth2
