// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ack.proto

package cn.v5cn.netty.ws.pb.core.entity;

public interface AckMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.v5cn.netty.ws.pb.generate.AckMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 协议版本号，第一个版本：1，以此类推。
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * 消息id
   * </pre>
   *
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *接受者类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType destType = 3;</code>
   * @return The enum numeric value on the wire for destType.
   */
  int getDestTypeValue();
  /**
   * <pre>
   *接受者类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType destType = 3;</code>
   * @return The destType.
   */
  cn.v5cn.netty.ws.pb.core.entity.AckMsg.DestType getDestType();

  /**
   * <pre>
   * 发送者userId
   * </pre>
   *
   * <code>string fromId = 4;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <pre>
   * 发送者userId
   * </pre>
   *
   * <code>string fromId = 4;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <pre>
   * 接收者userId
   * </pre>
   *
   * <code>string destId = 5;</code>
   * @return The destId.
   */
  java.lang.String getDestId();
  /**
   * <pre>
   * 接收者userId
   * </pre>
   *
   * <code>string destId = 5;</code>
   * @return The bytes for destId.
   */
  com.google.protobuf.ByteString
      getDestIdBytes();

  /**
   * <pre>
   * 发送时间
   * </pre>
   *
   * <code>int64 createTime = 6;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType msgType = 7;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType msgType = 7;</code>
   * @return The msgType.
   */
  cn.v5cn.netty.ws.pb.core.entity.AckMsg.MsgType getMsgType();

  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>int64 ackMsgId = 8;</code>
   * @return The ackMsgId.
   */
  long getAckMsgId();
}
