// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ack.proto

package cn.v5cn.netty.ws.pb.core.entity;

public final class AckWrapper {
  private AckWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_v5cn_netty_ws_pb_generate_AckMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_v5cn_netty_ws_pb_generate_AckMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tack.proto\022\034cn.v5cn.netty.ws.pb.generat" +
      "e\"\262\002\n\006AckMsg\022\017\n\007version\030\001 \001(\005\022\n\n\002id\030\002 \001(" +
      "\003\022?\n\010destType\030\003 \001(\0162-.cn.v5cn.netty.ws.p" +
      "b.generate.AckMsg.DestType\022\016\n\006fromId\030\004 \001" +
      "(\t\022\016\n\006destId\030\005 \001(\t\022\022\n\ncreateTime\030\006 \001(\003\022=" +
      "\n\007msgType\030\007 \001(\0162,.cn.v5cn.netty.ws.pb.ge" +
      "nerate.AckMsg.MsgType\022\020\n\010ackMsgId\030\010 \001(\003\"" +
      "!\n\010DestType\022\n\n\006SINGLE\020\000\022\t\n\005GROUP\020\001\"\"\n\007Ms" +
      "gType\022\r\n\tDELIVERED\020\000\022\010\n\004READ\020\001B/\n\037cn.v5c" +
      "n.netty.ws.pb.core.entityB\nAckWrapperP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_v5cn_netty_ws_pb_generate_AckMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_v5cn_netty_ws_pb_generate_AckMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_v5cn_netty_ws_pb_generate_AckMsg_descriptor,
        new java.lang.String[] { "Version", "Id", "DestType", "FromId", "DestId", "CreateTime", "MsgType", "AckMsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
