// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package cn.v5cn.netty.ws.pb.core.entity;

public interface ChatMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.v5cn.netty.ws.pb.generate.ChatMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *协议版本号。第一版本：1，以此类推。
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *接收者类型。
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
   * @return The enum numeric value on the wire for destType.
   */
  int getDestTypeValue();
  /**
   * <pre>
   *接收者类型。
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
   * @return The destType.
   */
  cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType getDestType();

  /**
   * <pre>
   *发送者userId
   * </pre>
   *
   * <code>string fromId = 4;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <pre>
   *发送者userId
   * </pre>
   *
   * <code>string fromId = 4;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <pre>
   *接收者userId
   * </pre>
   *
   * <code>string destId = 5;</code>
   * @return The destId.
   */
  java.lang.String getDestId();
  /**
   * <pre>
   *接收者userId
   * </pre>
   *
   * <code>string destId = 5;</code>
   * @return The bytes for destId.
   */
  com.google.protobuf.ByteString
      getDestIdBytes();

  /**
   * <pre>
   *发送时间
   * </pre>
   *
   * <code>int64 createTime = 6;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
   * @return The msgType.
   */
  cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType getMsgType();

  /**
   * <pre>
   *消息体，json，格式由消息类型决定
   * </pre>
   *
   * <code>bytes msgBody = 8;</code>
   * @return The msgBody.
   */
  com.google.protobuf.ByteString getMsgBody();

  /**
   * <code>optional string addition = 32;</code>
   * @return Whether the addition field is set.
   */
  boolean hasAddition();
  /**
   * <code>optional string addition = 32;</code>
   * @return The addition.
   */
  java.lang.String getAddition();
  /**
   * <code>optional string addition = 32;</code>
   * @return The bytes for addition.
   */
  com.google.protobuf.ByteString
      getAdditionBytes();
}
