// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package cn.v5cn.netty.ws.pb.core.entity;

public final class ChatWrapper {
  private ChatWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_v5cn_netty_ws_pb_generate_TextBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_v5cn_netty_ws_pb_generate_TextBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\034cn.v5cn.netty.ws.pb.genera" +
      "te\"\323\002\n\007ChatMsg\022\017\n\007version\030\001 \001(\005\022\n\n\002id\030\002 " +
      "\001(\003\022@\n\010destType\030\003 \001(\0162..cn.v5cn.netty.ws" +
      ".pb.generate.ChatMsg.DestType\022\016\n\006fromId\030" +
      "\004 \001(\t\022\016\n\006destId\030\005 \001(\t\022\022\n\ncreateTime\030\006 \001(" +
      "\003\022>\n\007msgType\030\007 \001(\0162-.cn.v5cn.netty.ws.pb" +
      ".generate.ChatMsg.MsgType\022\017\n\007msgBody\030\010 \001" +
      "(\014\022\025\n\010addition\030  \001(\tH\000\210\001\001\"!\n\010DestType\022\n\n" +
      "\006SINGLE\020\000\022\t\n\005GROUP\020\001\"\035\n\007MsgType\022\010\n\004TEXT\020" +
      "\000\022\010\n\004FILE\020\001B\013\n\t_addition\"\030\n\010TextBody\022\014\n\004" +
      "text\030\001 \001(\t\"M\n\010FileBody\022\016\n\006fileId\030\001 \001(\t\022\023" +
      "\n\013media_crc32\030\002 \001(\005\022\r\n\005fSize\030\003 \001(\005\022\r\n\005fN" +
      "ame\030\004 \001(\tB0\n\037cn.v5cn.netty.ws.pb.core.en" +
      "tityB\013ChatWrapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_descriptor,
        new java.lang.String[] { "Version", "Id", "DestType", "FromId", "DestId", "CreateTime", "MsgType", "MsgBody", "Addition", "Addition", });
    internal_static_cn_v5cn_netty_ws_pb_generate_TextBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_v5cn_netty_ws_pb_generate_TextBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_v5cn_netty_ws_pb_generate_TextBody_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_descriptor,
        new java.lang.String[] { "FileId", "MediaCrc32", "FSize", "FName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
