// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package cn.v5cn.netty.ws.pb.core.entity;

/**
 * Protobuf type {@code cn.v5cn.netty.ws.pb.generate.ChatMsg}
 */
public final class ChatMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.v5cn.netty.ws.pb.generate.ChatMsg)
    ChatMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMsg.newBuilder() to construct.
  private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMsg() {
    destType_ = 0;
    fromId_ = "";
    destId_ = "";
    msgType_ = 0;
    msgBody_ = com.google.protobuf.ByteString.EMPTY;
    addition_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMsg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            id_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            destType_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fromId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            destId_ = s;
            break;
          }
          case 48: {

            createTime_ = input.readInt64();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            msgType_ = rawValue;
            break;
          }
          case 66: {

            msgBody_ = input.readBytes();
            break;
          }
          case 258: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            addition_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.v5cn.netty.ws.pb.core.entity.ChatMsg.class, cn.v5cn.netty.ws.pb.core.entity.ChatMsg.Builder.class);
  }

  /**
   * Protobuf enum {@code cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType}
   */
  public enum DestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SINGLE = 0;</code>
     */
    SINGLE(0),
    /**
     * <code>GROUP = 1;</code>
     */
    GROUP(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SINGLE = 0;</code>
     */
    public static final int SINGLE_VALUE = 0;
    /**
     * <code>GROUP = 1;</code>
     */
    public static final int GROUP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DestType forNumber(int value) {
      switch (value) {
        case 0: return SINGLE;
        case 1: return GROUP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DestType>() {
            public DestType findValueByNumber(int number) {
              return DestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final DestType[] VALUES = values();

    public static DestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType)
  }

  /**
   * Protobuf enum {@code cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <code>FILE = 1;</code>
     */
    FILE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <code>FILE = 1;</code>
     */
    public static final int FILE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return FILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType)
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <pre>
   *协议版本号。第一版本：1，以此类推。
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_;
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int DESTTYPE_FIELD_NUMBER = 3;
  private int destType_;
  /**
   * <pre>
   *接收者类型。
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
   * @return The enum numeric value on the wire for destType.
   */
  @java.lang.Override public int getDestTypeValue() {
    return destType_;
  }
  /**
   * <pre>
   *接收者类型。
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
   * @return The destType.
   */
  @java.lang.Override public cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType getDestType() {
    @SuppressWarnings("deprecation")
    cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType result = cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType.valueOf(destType_);
    return result == null ? cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType.UNRECOGNIZED : result;
  }

  public static final int FROMID_FIELD_NUMBER = 4;
  private volatile java.lang.Object fromId_;
  /**
   * <pre>
   *发送者userId
   * </pre>
   *
   * <code>string fromId = 4;</code>
   * @return The fromId.
   */
  @java.lang.Override
  public java.lang.String getFromId() {
    java.lang.Object ref = fromId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发送者userId
   * </pre>
   *
   * <code>string fromId = 4;</code>
   * @return The bytes for fromId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromIdBytes() {
    java.lang.Object ref = fromId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTID_FIELD_NUMBER = 5;
  private volatile java.lang.Object destId_;
  /**
   * <pre>
   *接收者userId
   * </pre>
   *
   * <code>string destId = 5;</code>
   * @return The destId.
   */
  @java.lang.Override
  public java.lang.String getDestId() {
    java.lang.Object ref = destId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *接收者userId
   * </pre>
   *
   * <code>string destId = 5;</code>
   * @return The bytes for destId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestIdBytes() {
    java.lang.Object ref = destId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATETIME_FIELD_NUMBER = 6;
  private long createTime_;
  /**
   * <pre>
   *发送时间
   * </pre>
   *
   * <code>int64 createTime = 6;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public long getCreateTime() {
    return createTime_;
  }

  public static final int MSGTYPE_FIELD_NUMBER = 7;
  private int msgType_;
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  @java.lang.Override public int getMsgTypeValue() {
    return msgType_;
  }
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
   * @return The msgType.
   */
  @java.lang.Override public cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType getMsgType() {
    @SuppressWarnings("deprecation")
    cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType result = cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType.valueOf(msgType_);
    return result == null ? cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType.UNRECOGNIZED : result;
  }

  public static final int MSGBODY_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString msgBody_;
  /**
   * <pre>
   *消息体，json，格式由消息类型决定
   * </pre>
   *
   * <code>bytes msgBody = 8;</code>
   * @return The msgBody.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMsgBody() {
    return msgBody_;
  }

  public static final int ADDITION_FIELD_NUMBER = 32;
  private volatile java.lang.Object addition_;
  /**
   * <code>optional string addition = 32;</code>
   * @return Whether the addition field is set.
   */
  @java.lang.Override
  public boolean hasAddition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string addition = 32;</code>
   * @return The addition.
   */
  @java.lang.Override
  public java.lang.String getAddition() {
    java.lang.Object ref = addition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addition_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addition = 32;</code>
   * @return The bytes for addition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdditionBytes() {
    java.lang.Object ref = addition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (id_ != 0L) {
      output.writeInt64(2, id_);
    }
    if (destType_ != cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType.SINGLE.getNumber()) {
      output.writeEnum(3, destType_);
    }
    if (!getFromIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromId_);
    }
    if (!getDestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destId_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(6, createTime_);
    }
    if (msgType_ != cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType.TEXT.getNumber()) {
      output.writeEnum(7, msgType_);
    }
    if (!msgBody_.isEmpty()) {
      output.writeBytes(8, msgBody_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 32, addition_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, id_);
    }
    if (destType_ != cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType.SINGLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, destType_);
    }
    if (!getFromIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromId_);
    }
    if (!getDestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destId_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, createTime_);
    }
    if (msgType_ != cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType.TEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, msgType_);
    }
    if (!msgBody_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, msgBody_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(32, addition_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.v5cn.netty.ws.pb.core.entity.ChatMsg)) {
      return super.equals(obj);
    }
    cn.v5cn.netty.ws.pb.core.entity.ChatMsg other = (cn.v5cn.netty.ws.pb.core.entity.ChatMsg) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getId()
        != other.getId()) return false;
    if (destType_ != other.destType_) return false;
    if (!getFromId()
        .equals(other.getFromId())) return false;
    if (!getDestId()
        .equals(other.getDestId())) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (msgType_ != other.msgType_) return false;
    if (!getMsgBody()
        .equals(other.getMsgBody())) return false;
    if (hasAddition() != other.hasAddition()) return false;
    if (hasAddition()) {
      if (!getAddition()
          .equals(other.getAddition())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + DESTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + destType_;
    hash = (37 * hash) + FROMID_FIELD_NUMBER;
    hash = (53 * hash) + getFromId().hashCode();
    hash = (37 * hash) + DESTID_FIELD_NUMBER;
    hash = (53 * hash) + getDestId().hashCode();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + msgType_;
    hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
    hash = (53 * hash) + getMsgBody().hashCode();
    if (hasAddition()) {
      hash = (37 * hash) + ADDITION_FIELD_NUMBER;
      hash = (53 * hash) + getAddition().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.v5cn.netty.ws.pb.core.entity.ChatMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.v5cn.netty.ws.pb.generate.ChatMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.v5cn.netty.ws.pb.generate.ChatMsg)
      cn.v5cn.netty.ws.pb.core.entity.ChatMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.v5cn.netty.ws.pb.core.entity.ChatMsg.class, cn.v5cn.netty.ws.pb.core.entity.ChatMsg.Builder.class);
    }

    // Construct using cn.v5cn.netty.ws.pb.core.entity.ChatMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      id_ = 0L;

      destType_ = 0;

      fromId_ = "";

      destId_ = "";

      createTime_ = 0L;

      msgType_ = 0;

      msgBody_ = com.google.protobuf.ByteString.EMPTY;

      addition_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_ChatMsg_descriptor;
    }

    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.ChatMsg getDefaultInstanceForType() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatMsg.getDefaultInstance();
    }

    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.ChatMsg build() {
      cn.v5cn.netty.ws.pb.core.entity.ChatMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.ChatMsg buildPartial() {
      cn.v5cn.netty.ws.pb.core.entity.ChatMsg result = new cn.v5cn.netty.ws.pb.core.entity.ChatMsg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      result.id_ = id_;
      result.destType_ = destType_;
      result.fromId_ = fromId_;
      result.destId_ = destId_;
      result.createTime_ = createTime_;
      result.msgType_ = msgType_;
      result.msgBody_ = msgBody_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.addition_ = addition_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.v5cn.netty.ws.pb.core.entity.ChatMsg) {
        return mergeFrom((cn.v5cn.netty.ws.pb.core.entity.ChatMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.v5cn.netty.ws.pb.core.entity.ChatMsg other) {
      if (other == cn.v5cn.netty.ws.pb.core.entity.ChatMsg.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.destType_ != 0) {
        setDestTypeValue(other.getDestTypeValue());
      }
      if (!other.getFromId().isEmpty()) {
        fromId_ = other.fromId_;
        onChanged();
      }
      if (!other.getDestId().isEmpty()) {
        destId_ = other.destId_;
        onChanged();
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.msgType_ != 0) {
        setMsgTypeValue(other.getMsgTypeValue());
      }
      if (other.getMsgBody() != com.google.protobuf.ByteString.EMPTY) {
        setMsgBody(other.getMsgBody());
      }
      if (other.hasAddition()) {
        bitField0_ |= 0x00000001;
        addition_ = other.addition_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.v5cn.netty.ws.pb.core.entity.ChatMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.v5cn.netty.ws.pb.core.entity.ChatMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int destType_ = 0;
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
     * @return The enum numeric value on the wire for destType.
     */
    @java.lang.Override public int getDestTypeValue() {
      return destType_;
    }
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
     * @param value The enum numeric value on the wire for destType to set.
     * @return This builder for chaining.
     */
    public Builder setDestTypeValue(int value) {
      
      destType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
     * @return The destType.
     */
    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType getDestType() {
      @SuppressWarnings("deprecation")
      cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType result = cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType.valueOf(destType_);
      return result == null ? cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
     * @param value The destType to set.
     * @return This builder for chaining.
     */
    public Builder setDestType(cn.v5cn.netty.ws.pb.core.entity.ChatMsg.DestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      destType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType destType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestType() {
      
      destType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object fromId_ = "";
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     * @return The fromId.
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     * @return The bytes for fromId.
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     * @param value The fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromId() {
      
      fromId_ = getDefaultInstance().getFromId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     * @param value The bytes for fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destId_ = "";
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 5;</code>
     * @return The destId.
     */
    public java.lang.String getDestId() {
      java.lang.Object ref = destId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 5;</code>
     * @return The bytes for destId.
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      java.lang.Object ref = destId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 5;</code>
     * @param value The destId to set.
     * @return This builder for chaining.
     */
    public Builder setDestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestId() {
      
      destId_ = getDefaultInstance().getDestId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 5;</code>
     * @param value The bytes for destId to set.
     * @return This builder for chaining.
     */
    public Builder setDestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destId_ = value;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private int msgType_ = 0;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
     * @param value The enum numeric value on the wire for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeValue(int value) {
      
      msgType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType result = cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType.valueOf(msgType_);
      return result == null ? cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(cn.v5cn.netty.ws.pb.core.entity.ChatMsg.MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType msgType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      
      msgType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>bytes msgBody = 8;</code>
     * @return The msgBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>bytes msgBody = 8;</code>
     * @param value The msgBody to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgBody_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>bytes msgBody = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgBody() {
      
      msgBody_ = getDefaultInstance().getMsgBody();
      onChanged();
      return this;
    }

    private java.lang.Object addition_ = "";
    /**
     * <code>optional string addition = 32;</code>
     * @return Whether the addition field is set.
     */
    public boolean hasAddition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string addition = 32;</code>
     * @return The addition.
     */
    public java.lang.String getAddition() {
      java.lang.Object ref = addition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string addition = 32;</code>
     * @return The bytes for addition.
     */
    public com.google.protobuf.ByteString
        getAdditionBytes() {
      java.lang.Object ref = addition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addition = 32;</code>
     * @param value The addition to set.
     * @return This builder for chaining.
     */
    public Builder setAddition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      addition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addition = 32;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddition() {
      bitField0_ = (bitField0_ & ~0x00000001);
      addition_ = getDefaultInstance().getAddition();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addition = 32;</code>
     * @param value The bytes for addition to set.
     * @return This builder for chaining.
     */
    public Builder setAdditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      addition_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.v5cn.netty.ws.pb.generate.ChatMsg)
  }

  // @@protoc_insertion_point(class_scope:cn.v5cn.netty.ws.pb.generate.ChatMsg)
  private static final cn.v5cn.netty.ws.pb.core.entity.ChatMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.v5cn.netty.ws.pb.core.entity.ChatMsg();
  }

  public static cn.v5cn.netty.ws.pb.core.entity.ChatMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMsg>
      PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
    @java.lang.Override
    public ChatMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.v5cn.netty.ws.pb.core.entity.ChatMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

