// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package cn.v5cn.netty.ws.pb.core.entity;

/**
 * Protobuf type {@code cn.v5cn.netty.ws.pb.generate.FileBody}
 */
public final class FileBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.v5cn.netty.ws.pb.generate.FileBody)
    FileBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileBody.newBuilder() to construct.
  private FileBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileBody() {
    fileId_ = "";
    fName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileBody();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fileId_ = s;
            break;
          }
          case 16: {

            mediaCrc32_ = input.readInt32();
            break;
          }
          case 24: {

            fSize_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.v5cn.netty.ws.pb.core.entity.FileBody.class, cn.v5cn.netty.ws.pb.core.entity.FileBody.Builder.class);
  }

  public static final int FILEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object fileId_;
  /**
   * <pre>
   * 媒体文件上传得到的KEY,用于生成下载URL
   * </pre>
   *
   * <code>string fileId = 1;</code>
   * @return The fileId.
   */
  @java.lang.Override
  public java.lang.String getFileId() {
    java.lang.Object ref = fileId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 媒体文件上传得到的KEY,用于生成下载URL
   * </pre>
   *
   * <code>string fileId = 1;</code>
   * @return The bytes for fileId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileIdBytes() {
    java.lang.Object ref = fileId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIA_CRC32_FIELD_NUMBER = 2;
  private int mediaCrc32_;
  /**
   * <pre>
   * 文件的CRC32校验码
   * </pre>
   *
   * <code>int32 media_crc32 = 2;</code>
   * @return The mediaCrc32.
   */
  @java.lang.Override
  public int getMediaCrc32() {
    return mediaCrc32_;
  }

  public static final int FSIZE_FIELD_NUMBER = 3;
  private int fSize_;
  /**
   * <pre>
   * 文件大小（字节数）
   * </pre>
   *
   * <code>int32 fSize = 3;</code>
   * @return The fSize.
   */
  @java.lang.Override
  public int getFSize() {
    return fSize_;
  }

  public static final int FNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object fName_;
  /**
   * <pre>
   * 文件名称
   * </pre>
   *
   * <code>string fName = 4;</code>
   * @return The fName.
   */
  @java.lang.Override
  public java.lang.String getFName() {
    java.lang.Object ref = fName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文件名称
   * </pre>
   *
   * <code>string fName = 4;</code>
   * @return The bytes for fName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFNameBytes() {
    java.lang.Object ref = fName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileId_);
    }
    if (mediaCrc32_ != 0) {
      output.writeInt32(2, mediaCrc32_);
    }
    if (fSize_ != 0) {
      output.writeInt32(3, fSize_);
    }
    if (!getFNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileId_);
    }
    if (mediaCrc32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, mediaCrc32_);
    }
    if (fSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, fSize_);
    }
    if (!getFNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.v5cn.netty.ws.pb.core.entity.FileBody)) {
      return super.equals(obj);
    }
    cn.v5cn.netty.ws.pb.core.entity.FileBody other = (cn.v5cn.netty.ws.pb.core.entity.FileBody) obj;

    if (!getFileId()
        .equals(other.getFileId())) return false;
    if (getMediaCrc32()
        != other.getMediaCrc32()) return false;
    if (getFSize()
        != other.getFSize()) return false;
    if (!getFName()
        .equals(other.getFName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILEID_FIELD_NUMBER;
    hash = (53 * hash) + getFileId().hashCode();
    hash = (37 * hash) + MEDIA_CRC32_FIELD_NUMBER;
    hash = (53 * hash) + getMediaCrc32();
    hash = (37 * hash) + FSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFSize();
    hash = (37 * hash) + FNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.v5cn.netty.ws.pb.core.entity.FileBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.v5cn.netty.ws.pb.core.entity.FileBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.v5cn.netty.ws.pb.generate.FileBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.v5cn.netty.ws.pb.generate.FileBody)
      cn.v5cn.netty.ws.pb.core.entity.FileBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.v5cn.netty.ws.pb.core.entity.FileBody.class, cn.v5cn.netty.ws.pb.core.entity.FileBody.Builder.class);
    }

    // Construct using cn.v5cn.netty.ws.pb.core.entity.FileBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fileId_ = "";

      mediaCrc32_ = 0;

      fSize_ = 0;

      fName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.v5cn.netty.ws.pb.core.entity.ChatWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_FileBody_descriptor;
    }

    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.FileBody getDefaultInstanceForType() {
      return cn.v5cn.netty.ws.pb.core.entity.FileBody.getDefaultInstance();
    }

    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.FileBody build() {
      cn.v5cn.netty.ws.pb.core.entity.FileBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.v5cn.netty.ws.pb.core.entity.FileBody buildPartial() {
      cn.v5cn.netty.ws.pb.core.entity.FileBody result = new cn.v5cn.netty.ws.pb.core.entity.FileBody(this);
      result.fileId_ = fileId_;
      result.mediaCrc32_ = mediaCrc32_;
      result.fSize_ = fSize_;
      result.fName_ = fName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.v5cn.netty.ws.pb.core.entity.FileBody) {
        return mergeFrom((cn.v5cn.netty.ws.pb.core.entity.FileBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.v5cn.netty.ws.pb.core.entity.FileBody other) {
      if (other == cn.v5cn.netty.ws.pb.core.entity.FileBody.getDefaultInstance()) return this;
      if (!other.getFileId().isEmpty()) {
        fileId_ = other.fileId_;
        onChanged();
      }
      if (other.getMediaCrc32() != 0) {
        setMediaCrc32(other.getMediaCrc32());
      }
      if (other.getFSize() != 0) {
        setFSize(other.getFSize());
      }
      if (!other.getFName().isEmpty()) {
        fName_ = other.fName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.v5cn.netty.ws.pb.core.entity.FileBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.v5cn.netty.ws.pb.core.entity.FileBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fileId_ = "";
    /**
     * <pre>
     * 媒体文件上传得到的KEY,用于生成下载URL
     * </pre>
     *
     * <code>string fileId = 1;</code>
     * @return The fileId.
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 媒体文件上传得到的KEY,用于生成下载URL
     * </pre>
     *
     * <code>string fileId = 1;</code>
     * @return The bytes for fileId.
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 媒体文件上传得到的KEY,用于生成下载URL
     * </pre>
     *
     * <code>string fileId = 1;</code>
     * @param value The fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 媒体文件上传得到的KEY,用于生成下载URL
     * </pre>
     *
     * <code>string fileId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileId() {
      
      fileId_ = getDefaultInstance().getFileId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 媒体文件上传得到的KEY,用于生成下载URL
     * </pre>
     *
     * <code>string fileId = 1;</code>
     * @param value The bytes for fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileId_ = value;
      onChanged();
      return this;
    }

    private int mediaCrc32_ ;
    /**
     * <pre>
     * 文件的CRC32校验码
     * </pre>
     *
     * <code>int32 media_crc32 = 2;</code>
     * @return The mediaCrc32.
     */
    @java.lang.Override
    public int getMediaCrc32() {
      return mediaCrc32_;
    }
    /**
     * <pre>
     * 文件的CRC32校验码
     * </pre>
     *
     * <code>int32 media_crc32 = 2;</code>
     * @param value The mediaCrc32 to set.
     * @return This builder for chaining.
     */
    public Builder setMediaCrc32(int value) {
      
      mediaCrc32_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件的CRC32校验码
     * </pre>
     *
     * <code>int32 media_crc32 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaCrc32() {
      
      mediaCrc32_ = 0;
      onChanged();
      return this;
    }

    private int fSize_ ;
    /**
     * <pre>
     * 文件大小（字节数）
     * </pre>
     *
     * <code>int32 fSize = 3;</code>
     * @return The fSize.
     */
    @java.lang.Override
    public int getFSize() {
      return fSize_;
    }
    /**
     * <pre>
     * 文件大小（字节数）
     * </pre>
     *
     * <code>int32 fSize = 3;</code>
     * @param value The fSize to set.
     * @return This builder for chaining.
     */
    public Builder setFSize(int value) {
      
      fSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件大小（字节数）
     * </pre>
     *
     * <code>int32 fSize = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFSize() {
      
      fSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object fName_ = "";
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fName = 4;</code>
     * @return The fName.
     */
    public java.lang.String getFName() {
      java.lang.Object ref = fName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fName = 4;</code>
     * @return The bytes for fName.
     */
    public com.google.protobuf.ByteString
        getFNameBytes() {
      java.lang.Object ref = fName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fName = 4;</code>
     * @param value The fName to set.
     * @return This builder for chaining.
     */
    public Builder setFName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFName() {
      
      fName_ = getDefaultInstance().getFName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件名称
     * </pre>
     *
     * <code>string fName = 4;</code>
     * @param value The bytes for fName to set.
     * @return This builder for chaining.
     */
    public Builder setFNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.v5cn.netty.ws.pb.generate.FileBody)
  }

  // @@protoc_insertion_point(class_scope:cn.v5cn.netty.ws.pb.generate.FileBody)
  private static final cn.v5cn.netty.ws.pb.core.entity.FileBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.v5cn.netty.ws.pb.core.entity.FileBody();
  }

  public static cn.v5cn.netty.ws.pb.core.entity.FileBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileBody>
      PARSER = new com.google.protobuf.AbstractParser<FileBody>() {
    @java.lang.Override
    public FileBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.v5cn.netty.ws.pb.core.entity.FileBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

