// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package cn.v5cn.netty.ws.pb.core.entity;

public final class InternalWrapper {
  private InternalWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016internal.proto\022\034cn.v5cn.netty.ws.pb.ge" +
      "nerate\"\201\003\n\013InternalMsg\022\017\n\007version\030\001 \001(\005\022" +
      "\n\n\002id\030\002 \001(\003\022>\n\004from\030\003 \001(\01620.cn.v5cn.nett" +
      "y.ws.pb.generate.InternalMsg.Module\022>\n\004d" +
      "est\030\004 \001(\01620.cn.v5cn.netty.ws.pb.generate" +
      ".InternalMsg.Module\022\022\n\ncreateTime\030\005 \001(\003\022" +
      "B\n\007msgType\030\006 \001(\01621.cn.v5cn.netty.ws.pb.g" +
      "enerate.InternalMsg.MsgType\022\024\n\007msgBody\030\007" +
      " \001(\tH\000\210\001\001\"1\n\006Module\022\r\n\tCONNECTOR\020\000\022\014\n\010TR" +
      "ANSFER\020\001\022\n\n\006CLIENT\020\002\"(\n\007MsgType\022\t\n\005GREET" +
      "\020\000\022\007\n\003ACK\020\001\022\t\n\005ERROR\020\002B\n\n\010_msgBodyB4\n\037cn" +
      ".v5cn.netty.ws.pb.core.entityB\017InternalW" +
      "rapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_descriptor,
        new String[] { "Version", "Id", "From", "Dest", "CreateTime", "MsgType", "MsgBody", "MsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
