// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package cn.v5cn.netty.ws.pb.core.entity;

/**
 * Protobuf type {@code cn.v5cn.netty.ws.pb.generate.InternalMsg}
 */
public final class InternalMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.v5cn.netty.ws.pb.generate.InternalMsg)
    InternalMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InternalMsg.newBuilder() to construct.
  private InternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InternalMsg() {
    from_ = 0;
    dest_ = 0;
    msgType_ = 0;
    msgBody_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new InternalMsg();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InternalMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            id_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            from_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            dest_ = rawValue;
            break;
          }
          case 40: {

            createTime_ = input.readInt64();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            msgType_ = rawValue;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            msgBody_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return InternalWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return InternalWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InternalMsg.class, Builder.class);
  }

  /**
   * Protobuf enum {@code cn.v5cn.netty.ws.pb.generate.InternalMsg.Module}
   */
  public enum Module
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONNECTOR = 0;</code>
     */
    CONNECTOR(0),
    /**
     * <code>TRANSFER = 1;</code>
     */
    TRANSFER(1),
    /**
     * <code>CLIENT = 2;</code>
     */
    CLIENT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CONNECTOR = 0;</code>
     */
    public static final int CONNECTOR_VALUE = 0;
    /**
     * <code>TRANSFER = 1;</code>
     */
    public static final int TRANSFER_VALUE = 1;
    /**
     * <code>CLIENT = 2;</code>
     */
    public static final int CLIENT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Module valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Module forNumber(int value) {
      switch (value) {
        case 0: return CONNECTOR;
        case 1: return TRANSFER;
        case 2: return CLIENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Module> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Module>() {
            public Module findValueByNumber(int number) {
              return Module.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return InternalMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final Module[] VALUES = values();

    public static Module valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Module(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.v5cn.netty.ws.pb.generate.InternalMsg.Module)
  }

  /**
   * Protobuf enum {@code cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GREET = 0;</code>
     */
    GREET(0),
    /**
     * <code>ACK = 1;</code>
     */
    ACK(1),
    /**
     * <code>ERROR = 2;</code>
     */
    ERROR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GREET = 0;</code>
     */
    public static final int GREET_VALUE = 0;
    /**
     * <code>ACK = 1;</code>
     */
    public static final int ACK_VALUE = 1;
    /**
     * <code>ERROR = 2;</code>
     */
    public static final int ERROR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return GREET;
        case 1: return ACK;
        case 2: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return InternalMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType)
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <pre>
   *协议版本号。第一版本：1，以此类推。
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @Override
  public int getVersion() {
    return version_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_;
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  public static final int FROM_FIELD_NUMBER = 3;
  private int from_;
  /**
   * <pre>
   *发送模块
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
   * @return The enum numeric value on the wire for from.
   */
  @Override public int getFromValue() {
    return from_;
  }
  /**
   * <pre>
   *发送模块
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
   * @return The from.
   */
  @Override public Module getFrom() {
    @SuppressWarnings("deprecation")
    Module result = Module.valueOf(from_);
    return result == null ? Module.UNRECOGNIZED : result;
  }

  public static final int DEST_FIELD_NUMBER = 4;
  private int dest_;
  /**
   * <pre>
   *接收模块
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
   * @return The enum numeric value on the wire for dest.
   */
  @Override public int getDestValue() {
    return dest_;
  }
  /**
   * <pre>
   *接收模块
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
   * @return The dest.
   */
  @Override public Module getDest() {
    @SuppressWarnings("deprecation")
    Module result = Module.valueOf(dest_);
    return result == null ? Module.UNRECOGNIZED : result;
  }

  public static final int CREATETIME_FIELD_NUMBER = 5;
  private long createTime_;
  /**
   * <pre>
   *发送时间
   * </pre>
   *
   * <code>int64 createTime = 5;</code>
   * @return The createTime.
   */
  @Override
  public long getCreateTime() {
    return createTime_;
  }

  public static final int MSGTYPE_FIELD_NUMBER = 6;
  private int msgType_;
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  @Override public int getMsgTypeValue() {
    return msgType_;
  }
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
   * @return The msgType.
   */
  @Override public MsgType getMsgType() {
    @SuppressWarnings("deprecation")
    MsgType result = MsgType.valueOf(msgType_);
    return result == null ? MsgType.UNRECOGNIZED : result;
  }

  public static final int MSGBODY_FIELD_NUMBER = 7;
  private volatile Object msgBody_;
  /**
   * <pre>
   *消息体
   * </pre>
   *
   * <code>optional string msgBody = 7;</code>
   * @return Whether the msgBody field is set.
   */
  @Override
  public boolean hasMsgBody() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *消息体
   * </pre>
   *
   * <code>optional string msgBody = 7;</code>
   * @return The msgBody.
   */
  @Override
  public String getMsgBody() {
    Object ref = msgBody_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msgBody_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *消息体
   * </pre>
   *
   * <code>optional string msgBody = 7;</code>
   * @return The bytes for msgBody.
   */
  @Override
  public com.google.protobuf.ByteString
      getMsgBodyBytes() {
    Object ref = msgBody_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msgBody_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (id_ != 0L) {
      output.writeInt64(2, id_);
    }
    if (from_ != Module.CONNECTOR.getNumber()) {
      output.writeEnum(3, from_);
    }
    if (dest_ != Module.CONNECTOR.getNumber()) {
      output.writeEnum(4, dest_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(5, createTime_);
    }
    if (msgType_ != MsgType.GREET.getNumber()) {
      output.writeEnum(6, msgType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgBody_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, id_);
    }
    if (from_ != Module.CONNECTOR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, from_);
    }
    if (dest_ != Module.CONNECTOR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, dest_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, createTime_);
    }
    if (msgType_ != MsgType.GREET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, msgType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InternalMsg)) {
      return super.equals(obj);
    }
    InternalMsg other = (InternalMsg) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getId()
        != other.getId()) return false;
    if (from_ != other.from_) return false;
    if (dest_ != other.dest_) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (msgType_ != other.msgType_) return false;
    if (hasMsgBody() != other.hasMsgBody()) return false;
    if (hasMsgBody()) {
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + from_;
    hash = (37 * hash) + DEST_FIELD_NUMBER;
    hash = (53 * hash) + dest_;
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + msgType_;
    if (hasMsgBody()) {
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InternalMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InternalMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InternalMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InternalMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InternalMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InternalMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InternalMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InternalMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InternalMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InternalMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InternalMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InternalMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InternalMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.v5cn.netty.ws.pb.generate.InternalMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.v5cn.netty.ws.pb.generate.InternalMsg)
      InternalMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InternalWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InternalWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InternalMsg.class, Builder.class);
    }

    // Construct using cn.v5cn.netty.ws.pb.core.entity.InternalMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      id_ = 0L;

      from_ = 0;

      dest_ = 0;

      createTime_ = 0L;

      msgType_ = 0;

      msgBody_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return InternalWrapper.internal_static_cn_v5cn_netty_ws_pb_generate_InternalMsg_descriptor;
    }

    @Override
    public InternalMsg getDefaultInstanceForType() {
      return InternalMsg.getDefaultInstance();
    }

    @Override
    public InternalMsg build() {
      InternalMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public InternalMsg buildPartial() {
      InternalMsg result = new InternalMsg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      result.id_ = id_;
      result.from_ = from_;
      result.dest_ = dest_;
      result.createTime_ = createTime_;
      result.msgType_ = msgType_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.msgBody_ = msgBody_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InternalMsg) {
        return mergeFrom((InternalMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InternalMsg other) {
      if (other == InternalMsg.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.from_ != 0) {
        setFromValue(other.getFromValue());
      }
      if (other.dest_ != 0) {
        setDestValue(other.getDestValue());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.msgType_ != 0) {
        setMsgTypeValue(other.getMsgTypeValue());
      }
      if (other.hasMsgBody()) {
        bitField0_ |= 0x00000001;
        msgBody_ = other.msgBody_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      InternalMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (InternalMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int from_ = 0;
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
     * @return The enum numeric value on the wire for from.
     */
    @Override public int getFromValue() {
      return from_;
    }
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
     * @param value The enum numeric value on the wire for from to set.
     * @return This builder for chaining.
     */
    public Builder setFromValue(int value) {
      
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
     * @return The from.
     */
    @Override
    public Module getFrom() {
      @SuppressWarnings("deprecation")
      Module result = Module.valueOf(from_);
      return result == null ? Module.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(Module value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      from_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module from = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      
      from_ = 0;
      onChanged();
      return this;
    }

    private int dest_ = 0;
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
     * @return The enum numeric value on the wire for dest.
     */
    @Override public int getDestValue() {
      return dest_;
    }
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
     * @param value The enum numeric value on the wire for dest to set.
     * @return This builder for chaining.
     */
    public Builder setDestValue(int value) {
      
      dest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
     * @return The dest.
     */
    @Override
    public Module getDest() {
      @SuppressWarnings("deprecation")
      Module result = Module.valueOf(dest_);
      return result == null ? Module.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
     * @param value The dest to set.
     * @return This builder for chaining.
     */
    public Builder setDest(Module value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dest_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module dest = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDest() {
      
      dest_ = 0;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 5;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 5;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private int msgType_ = 0;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
     * @param value The enum numeric value on the wire for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeValue(int value) {
      
      msgType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
     * @return The msgType.
     */
    @Override
    public MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      MsgType result = MsgType.valueOf(msgType_);
      return result == null ? MsgType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType msgType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      
      msgType_ = 0;
      onChanged();
      return this;
    }

    private Object msgBody_ = "";
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return Whether the msgBody field is set.
     */
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return The msgBody.
     */
    public String getMsgBody() {
      Object ref = msgBody_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgBody_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      Object ref = msgBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @param value The msgBody to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBody(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msgBody_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgBody() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgBody_ = getDefaultInstance().getMsgBody();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @param value The bytes for msgBody to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      msgBody_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.v5cn.netty.ws.pb.generate.InternalMsg)
  }

  // @@protoc_insertion_point(class_scope:cn.v5cn.netty.ws.pb.generate.InternalMsg)
  private static final InternalMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InternalMsg();
  }

  public static InternalMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InternalMsg>
      PARSER = new com.google.protobuf.AbstractParser<InternalMsg>() {
    @Override
    public InternalMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InternalMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InternalMsg> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InternalMsg> getParserForType() {
    return PARSER;
  }

  @Override
  public InternalMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

