// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package cn.v5cn.netty.ws.pb.core.entity;

public interface TextBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.v5cn.netty.ws.pb.generate.TextBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文字内容
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * 文字内容
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
