// source: ack.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.AckMsg', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cn.v5cn.netty.ws.pb.generate.AckMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cn.v5cn.netty.ws.pb.generate.AckMsg.displayName = 'proto.cn.v5cn.netty.ws.pb.generate.AckMsg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.cn.v5cn.netty.ws.pb.generate.AckMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, 0),
    desttype: jspb.Message.getFieldWithDefault(msg, 3, 0),
    fromid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    destid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    createtime: jspb.Message.getFieldWithDefault(msg, 6, 0),
    msgtype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    ackmsgid: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cn.v5cn.netty.ws.pb.generate.AckMsg;
  return proto.cn.v5cn.netty.ws.pb.generate.AckMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType} */ (reader.readEnum());
      msg.setDesttype(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatetime(value);
      break;
    case 7:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAckmsgid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cn.v5cn.netty.ws.pb.generate.AckMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getDesttype();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getFromid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDestid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCreatetime();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getAckmsgid();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType = {
  SINGLE: 0,
  GROUP: 1
};

/**
 * @enum {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType = {
  DELIVERED: 0,
  READ: 1
};

/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 id = 2;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional DestType destType = 3;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getDesttype = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.DestType} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setDesttype = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string fromId = 4;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getFromid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setFromid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string destId = 5;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getDestid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setDestid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 createTime = 6;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getCreatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setCreatetime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional MsgType msgType = 7;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getMsgtype = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg.MsgType} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setMsgtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional int64 ackMsgId = 8;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.getAckmsgid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.AckMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.AckMsg.prototype.setAckmsgid = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


goog.object.extend(exports, proto.cn.v5cn.netty.ws.pb.generate);
