// source: chat.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.ChatMsg', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.FileBody', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.TextBody', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cn.v5cn.netty.ws.pb.generate.ChatMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.displayName = 'proto.cn.v5cn.netty.ws.pb.generate.ChatMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cn.v5cn.netty.ws.pb.generate.TextBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cn.v5cn.netty.ws.pb.generate.TextBody.displayName = 'proto.cn.v5cn.netty.ws.pb.generate.TextBody';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cn.v5cn.netty.ws.pb.generate.FileBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cn.v5cn.netty.ws.pb.generate.FileBody.displayName = 'proto.cn.v5cn.netty.ws.pb.generate.FileBody';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, 0),
    desttype: jspb.Message.getFieldWithDefault(msg, 3, 0),
    fromid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    destid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    createtime: jspb.Message.getFieldWithDefault(msg, 6, 0),
    msgtype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    msgbody: msg.getMsgbody_asB64(),
    addition: jspb.Message.getFieldWithDefault(msg, 32, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cn.v5cn.netty.ws.pb.generate.ChatMsg;
  return proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType} */ (reader.readEnum());
      msg.setDesttype(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatetime(value);
      break;
    case 7:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMsgbody(value);
      break;
    case 32:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getDesttype();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getFromid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDestid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCreatetime();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getMsgbody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 32));
  if (f != null) {
    writer.writeString(
      32,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType = {
  SINGLE: 0,
  GROUP: 1
};

/**
 * @enum {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType = {
  TEXT: 0,
  FILE: 1
};

/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 id = 2;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional DestType destType = 3;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getDesttype = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.DestType} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setDesttype = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string fromId = 4;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getFromid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setFromid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string destId = 5;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getDestid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setDestid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 createTime = 6;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getCreatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setCreatetime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional MsgType msgType = 7;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getMsgtype = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.MsgType} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setMsgtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional bytes msgBody = 8;
 * @return {!(string|Uint8Array)}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getMsgbody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes msgBody = 8;
 * This is a type-conversion wrapper around `getMsgbody()`
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getMsgbody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMsgbody()));
};


/**
 * optional bytes msgBody = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMsgbody()`
 * @return {!Uint8Array}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getMsgbody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMsgbody()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setMsgbody = function(value) {
  return jspb.Message.setProto3BytesField(this, 8, value);
};


/**
 * optional string addition = 32;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.getAddition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 32, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.setAddition = function(value) {
  return jspb.Message.setField(this, 32, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.ChatMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.clearAddition = function() {
  return jspb.Message.setField(this, 32, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cn.v5cn.netty.ws.pb.generate.ChatMsg.prototype.hasAddition = function() {
  return jspb.Message.getField(this, 32) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.prototype.toObject = function(opt_includeInstance) {
  return proto.cn.v5cn.netty.ws.pb.generate.TextBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.TextBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.TextBody}
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cn.v5cn.netty.ws.pb.generate.TextBody;
  return proto.cn.v5cn.netty.ws.pb.generate.TextBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.TextBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.TextBody}
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cn.v5cn.netty.ws.pb.generate.TextBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.TextBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.TextBody} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.TextBody.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.toObject = function(opt_includeInstance) {
  return proto.cn.v5cn.netty.ws.pb.generate.FileBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mediaCrc32: jspb.Message.getFieldWithDefault(msg, 2, 0),
    fsize: jspb.Message.getFieldWithDefault(msg, 3, 0),
    fname: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.FileBody}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cn.v5cn.netty.ws.pb.generate.FileBody;
  return proto.cn.v5cn.netty.ws.pb.generate.FileBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.FileBody}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMediaCrc32(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFsize(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cn.v5cn.netty.ws.pb.generate.FileBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMediaCrc32();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFsize();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getFname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string fileId = 1;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.getFileid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.setFileid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 media_crc32 = 2;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.getMediaCrc32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.setMediaCrc32 = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 fSize = 3;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.getFsize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.setFsize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string fName = 4;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.getFname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.FileBody} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.FileBody.prototype.setFname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.cn.v5cn.netty.ws.pb.generate);
