// source: internal.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.InternalMsg', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module', null, global);
goog.exportSymbol('proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cn.v5cn.netty.ws.pb.generate.InternalMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.displayName = 'proto.cn.v5cn.netty.ws.pb.generate.InternalMsg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, 0),
    from: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dest: jspb.Message.getFieldWithDefault(msg, 4, 0),
    createtime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    msgtype: jspb.Message.getFieldWithDefault(msg, 6, 0),
    msgbody: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cn.v5cn.netty.ws.pb.generate.InternalMsg;
  return proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module} */ (reader.readEnum());
      msg.setFrom(value);
      break;
    case 4:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module} */ (reader.readEnum());
      msg.setDest(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatetime(value);
      break;
    case 6:
      var value = /** @type {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsgbody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getFrom();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDest();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getCreatetime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module = {
  CONNECTOR: 0,
  TRANSFER: 1,
  CLIENT: 2
};

/**
 * @enum {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType = {
  GREET: 0,
  ACK: 1,
  ERROR: 2
};

/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 id = 2;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Module from = 3;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getFrom = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setFrom = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Module dest = 4;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getDest = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.Module} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setDest = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int64 createTime = 5;
 * @return {number}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getCreatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setCreatetime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional MsgType msgType = 6;
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getMsgtype = function() {
  return /** @type {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.MsgType} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setMsgtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional string msgBody = 7;
 * @return {string}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.getMsgbody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.setMsgbody = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.cn.v5cn.netty.ws.pb.generate.InternalMsg} returns this
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.clearMsgbody = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cn.v5cn.netty.ws.pb.generate.InternalMsg.prototype.hasMsgbody = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.cn.v5cn.netty.ws.pb.generate);
