# 创建PV
# PV 描述的，是持久化存储数据卷
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/"
    server: 10.244.1.4
---
# 创建PVC
# PVC 描述的，则是 Pod 所希望使用的持久化存储的属性
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  accessModes:
    - ReadWriteMany
  # PVC要和PV的名字相同
  storageClassName: storage-local
  resources:
    requests:
      storage: 1Gi

---
# 使用PVC

apiVersion: v1
kind: Pod
metadata:
  labels:
    role: web-frontend
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: local
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: local
      persistentVolumeClaim:
        claimName: local
  
  