// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package cn.v5cn.rpc.grpc;

/**
 * @author zhuyanwei
 */
public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
