// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseResponseProto.proto

package cn.v5cn.cim.common.protocol;

public final class CIMResponseProto {
  private CIMResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CIMResProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.CIMResProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 responseId = 2;</code>
     * @return The responseId.
     */
    long getResponseId();

    /**
     * <code>string resMsg = 1;</code>
     * @return The resMsg.
     */
    String getResMsg();
    /**
     * <code>string resMsg = 1;</code>
     * @return The bytes for resMsg.
     */
    com.google.protobuf.ByteString
        getResMsgBytes();

    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code protocol.CIMResProtocol}
   */
  public static final class CIMResProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.CIMResProtocol)
      CIMResProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CIMResProtocol.newBuilder() to construct.
    private CIMResProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CIMResProtocol() {
      resMsg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CIMResProtocol();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CIMResProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              resMsg_ = s;
              break;
            }
            case 16: {

              responseId_ = input.readInt64();
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CIMResponseProto.internal_static_protocol_CIMResProtocol_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CIMResponseProto.internal_static_protocol_CIMResProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CIMResProtocol.class, Builder.class);
    }

    public static final int RESPONSEID_FIELD_NUMBER = 2;
    private long responseId_;
    /**
     * <code>int64 responseId = 2;</code>
     * @return The responseId.
     */
    @Override
    public long getResponseId() {
      return responseId_;
    }

    public static final int RESMSG_FIELD_NUMBER = 1;
    private volatile Object resMsg_;
    /**
     * <code>string resMsg = 1;</code>
     * @return The resMsg.
     */
    @Override
    public String getResMsg() {
      Object ref = resMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string resMsg = 1;</code>
     * @return The bytes for resMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getResMsgBytes() {
      Object ref = resMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    @Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resMsg_);
      }
      if (responseId_ != 0L) {
        output.writeInt64(2, responseId_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resMsg_);
      }
      if (responseId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, responseId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CIMResProtocol)) {
        return super.equals(obj);
      }
      CIMResProtocol other = (CIMResProtocol) obj;

      if (getResponseId()
          != other.getResponseId()) return false;
      if (!getResMsg()
          .equals(other.getResMsg())) return false;
      if (getType()
          != other.getType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseId());
      hash = (37 * hash) + RESMSG_FIELD_NUMBER;
      hash = (53 * hash) + getResMsg().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CIMResProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CIMResProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CIMResProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CIMResProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CIMResProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CIMResProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CIMResProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CIMResProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CIMResProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CIMResProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CIMResProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CIMResProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CIMResProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.CIMResProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.CIMResProtocol)
        CIMResProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CIMResponseProto.internal_static_protocol_CIMResProtocol_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CIMResponseProto.internal_static_protocol_CIMResProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CIMResProtocol.class, Builder.class);
      }

      // Construct using cn.v5cn.cim.common.protocol.CIMResponseProto.CIMResProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        responseId_ = 0L;

        resMsg_ = "";

        type_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CIMResponseProto.internal_static_protocol_CIMResProtocol_descriptor;
      }

      @Override
      public CIMResProtocol getDefaultInstanceForType() {
        return CIMResProtocol.getDefaultInstance();
      }

      @Override
      public CIMResProtocol build() {
        CIMResProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CIMResProtocol buildPartial() {
        CIMResProtocol result = new CIMResProtocol(this);
        result.responseId_ = responseId_;
        result.resMsg_ = resMsg_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CIMResProtocol) {
          return mergeFrom((CIMResProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CIMResProtocol other) {
        if (other == CIMResProtocol.getDefaultInstance()) return this;
        if (other.getResponseId() != 0L) {
          setResponseId(other.getResponseId());
        }
        if (!other.getResMsg().isEmpty()) {
          resMsg_ = other.resMsg_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CIMResProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CIMResProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long responseId_ ;
      /**
       * <code>int64 responseId = 2;</code>
       * @return The responseId.
       */
      @Override
      public long getResponseId() {
        return responseId_;
      }
      /**
       * <code>int64 responseId = 2;</code>
       * @param value The responseId to set.
       * @return This builder for chaining.
       */
      public Builder setResponseId(long value) {
        
        responseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 responseId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseId() {
        
        responseId_ = 0L;
        onChanged();
        return this;
      }

      private Object resMsg_ = "";
      /**
       * <code>string resMsg = 1;</code>
       * @return The resMsg.
       */
      @Override
      public String getResMsg() {
        Object ref = resMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string resMsg = 1;</code>
       * @return The bytes for resMsg.
       */
      @Override
      public com.google.protobuf.ByteString
          getResMsgBytes() {
        Object ref = resMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resMsg = 1;</code>
       * @param value The resMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resMsg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResMsg() {
        
        resMsg_ = getDefaultInstance().getResMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string resMsg = 1;</code>
       * @param value The bytes for resMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resMsg_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 3;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.CIMResProtocol)
    }

    // @@protoc_insertion_point(class_scope:protocol.CIMResProtocol)
    private static final CIMResProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CIMResProtocol();
    }

    public static CIMResProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CIMResProtocol>
        PARSER = new com.google.protobuf.AbstractParser<CIMResProtocol>() {
      @Override
      public CIMResProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CIMResProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CIMResProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CIMResProtocol> getParserForType() {
      return PARSER;
    }

    @Override
    public CIMResProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CIMResProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CIMResProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027BaseResponseProto.proto\022\010protocol\"B\n\016C" +
      "IMResProtocol\022\022\n\nresponseId\030\002 \001(\003\022\016\n\006res" +
      "Msg\030\001 \001(\t\022\014\n\004type\030\003 \001(\005B1\n\033cn.v5cn.cim.c" +
      "ommon.protocolB\020CIMResponseProtoP\000b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_CIMResProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_CIMResProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CIMResProtocol_descriptor,
        new String[] { "ResponseId", "ResMsg", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
