server:
  port: 8083

spring:
  application:
    name: service1
  security:
    user:
      name: zhangsan
      password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:3000/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

logging:
  level:
    org.springframework: debug