server:
  port: 8084

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true
        namespace: public
  application:
    name: nacos-provider
