server:
  port: 3000
spring:
  application:
    name: eureka-server
  security:
    user:
      name: zhangsan
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

